var annotated_dup =
[
    [ "DeulPie", "namespace_deul_pie.html", [
      [ "ExtraInk", "namespace_deul_pie_1_1_extra_ink.html", [
        [ "Core", "namespace_deul_pie_1_1_extra_ink_1_1_core.html", [
          [ "Data", "namespace_deul_pie_1_1_extra_ink_1_1_core_1_1_data.html", [
            [ "DialogueData", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_data_1_1_dialogue_data.html", null ]
          ] ],
          [ "Events", "namespace_deul_pie_1_1_extra_ink_1_1_core_1_1_events.html", [
            [ "BaseEventChannel< T >", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_base_event_channel-1-g.html", null ],
            [ "BaseEventChannelListener< TEventData, TEventChannel >", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_base_event_channel_listener-2-g.html", null ],
            [ "DialogueEventChannel", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_dialogue_event_channel.html", null ],
            [ "DialogueEventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_dialogue_event_channel_listener.html", null ],
            [ "FloatEventChannel", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_float_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_float_event_channel" ],
            [ "FloatEventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_float_event_channel_listener.html", null ],
            [ "GameObjectEventChannel", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_game_object_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_game_object_event_channel" ],
            [ "GameObjectEventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_game_object_event_channel_listener.html", null ],
            [ "IntEventChannel", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_int_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_int_event_channel" ],
            [ "IntEventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_int_event_channel_listener.html", null ],
            [ "Vector3EventChannel", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_vector3_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_vector3_event_channel" ],
            [ "Vector3EventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_events_1_1_vector3_event_channel_listener.html", null ]
          ] ],
          [ "Interfaces", "namespace_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces.html", [
            [ "AudioSettings", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_audio_settings.html", null ],
            [ "DialogueEntry", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_dialogue_entry.html", null ],
            [ "GameplaySettings", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_gameplay_settings.html", null ],
            [ "IAudioEffectController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_audio_effect_controller.html", null ],
            [ "IAudioManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_audio_manager.html", null ],
            [ "IAudioPlayer", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_audio_player.html", null ],
            [ "IAudioResourceManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_audio_resource_manager.html", null ],
            [ "IAutoPlayController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_auto_play_controller.html", null ],
            [ "IBackgroundManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_background_manager.html", null ],
            [ "ICharacterAnimationController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_character_animation_controller.html", null ],
            [ "ICharacterDataManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_character_data_manager.html", null ],
            [ "ICharacterDisplay", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_character_display.html", null ],
            [ "ICharacterEmotionController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_character_emotion_controller.html", null ],
            [ "ICharacterManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_character_manager.html", null ],
            [ "ICharacterPositionController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_character_position_controller.html", null ],
            [ "ICharacterSkinController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_character_skin_controller.html", null ],
            [ "IChoiceController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_choice_controller.html", null ],
            [ "IConfigurable< TConfig >", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_configurable-1-g.html", null ],
            [ "IDialogueDisplay", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_dialogue_display.html", null ],
            [ "IDialogueHistory", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_dialogue_history.html", null ],
            [ "IDialogueManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_dialogue_manager.html", null ],
            [ "IDialogueStyleController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_dialogue_style_controller.html", null ],
            [ "IEventPublisher", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_event_publisher.html", null ],
            [ "IFadeController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_fade_controller.html", null ],
            [ "ILanguageManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_language_manager.html", null ],
            [ "ILocalizationManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_localization_manager.html", null ],
            [ "ILocalizationResourceManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_localization_resource_manager.html", null ],
            [ "ILocalizationTextProvider", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_localization_text_provider.html", null ],
            [ "ILoggable", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_loggable.html", null ],
            [ "IManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_manager.html", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_manager" ],
            [ "IPausable", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_pausable.html", null ],
            [ "IPrioritized", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_prioritized.html", null ],
            [ "IResourceManager< TResource >", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_resource_manager-1-g.html", null ],
            [ "ISceneManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_scene_manager.html", null ],
            [ "ISceneTransition", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_scene_transition.html", null ],
            [ "ISettingsCategoryManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_settings_category_manager.html", null ],
            [ "ISettingsManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_settings_manager.html", null ],
            [ "ISettingsPersistence", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_settings_persistence.html", null ],
            [ "ISettingsReader", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_settings_reader.html", null ],
            [ "ISettingsWriter", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_settings_writer.html", null ],
            [ "ISingleton< T >", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_singleton-1-g.html", null ],
            [ "IStatefulManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_stateful_manager.html", null ],
            [ "ITextAnimationController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_text_animation_controller.html", null ],
            [ "IUIAnimationController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_u_i_animation_controller.html", null ],
            [ "IUIDataBinder", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_u_i_data_binder.html", null ],
            [ "IUIDisplay", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_u_i_display.html", null ],
            [ "IUIManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_u_i_manager.html", null ],
            [ "IUIStateManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_u_i_state_manager.html", null ],
            [ "IUnityManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_unity_manager.html", null ],
            [ "IUpdatable", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_updatable.html", null ],
            [ "IVolumeController", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_i_volume_controller.html", null ],
            [ "UISettings", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_interfaces_1_1_u_i_settings.html", null ]
          ] ],
          [ "Managers", "namespace_deul_pie_1_1_extra_ink_1_1_core_1_1_managers.html", [
            [ "AudioManager", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_audio_manager.html", null ],
            [ "AudioSettings", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_audio_settings.html", null ],
            [ "BaseManager", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_base_manager.html", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_base_manager" ],
            [ "GameplaySettings", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_gameplay_settings.html", null ],
            [ "IAudioManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_i_audio_manager.html", null ],
            [ "IManagerLifecycle", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_i_manager_lifecycle.html", null ],
            [ "ISettingsManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_i_settings_manager.html", null ],
            [ "IUIManager", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_i_u_i_manager.html", null ],
            [ "IUIUpdatable", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_i_u_i_updatable.html", null ],
            [ "ManagerAdapter< T >", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_manager_adapter-1-g.html", null ],
            [ "ManagerBootstrapper", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_manager_bootstrapper.html", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_manager_bootstrapper" ],
            [ "ManagerConfigEntry", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_manager_config_entry.html", null ],
            [ "ManagerConfiguration", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_manager_configuration.html", null ],
            [ "ManagerFactory", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_manager_factory.html", null ],
            [ "SettingsManager", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_settings_manager.html", null ],
            [ "UILayoutData", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_u_i_layout_data.html", null ],
            [ "UIManager", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_u_i_manager.html", null ],
            [ "UIPanel", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_u_i_panel.html", null ],
            [ "UISettings", "struct_deul_pie_1_1_extra_ink_1_1_core_1_1_managers_1_1_u_i_settings.html", null ]
          ] ],
          [ "Settings", "namespace_deul_pie_1_1_extra_ink_1_1_core_1_1_settings.html", [
            [ "EncryptedFileSettingsStorage", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_settings_1_1_encrypted_file_settings_storage.html", null ],
            [ "ISettingsStorage", "interface_deul_pie_1_1_extra_ink_1_1_core_1_1_settings_1_1_i_settings_storage.html", null ],
            [ "JsonFileSettingsStorage", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_settings_1_1_json_file_settings_storage.html", null ],
            [ "PlayerPrefsSettingsStorage", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_settings_1_1_player_prefs_settings_storage.html", null ],
            [ "SettingItem", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_settings_1_1_setting_item.html", null ],
            [ "SettingsData", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_settings_1_1_settings_data.html", null ],
            [ "SettingsWrapper", "class_deul_pie_1_1_extra_ink_1_1_core_1_1_settings_1_1_settings_wrapper.html", null ]
          ] ]
        ] ],
        [ "Editor", "namespace_deul_pie_1_1_extra_ink_1_1_editor.html", [
          [ "Plugins", "namespace_deul_pie_1_1_extra_ink_1_1_editor_1_1_plugins.html", [
            [ "PluginCreatorWindow", "class_deul_pie_1_1_extra_ink_1_1_editor_1_1_plugins_1_1_plugin_creator_window.html", null ],
            [ "PluginManagerWindow", "class_deul_pie_1_1_extra_ink_1_1_editor_1_1_plugins_1_1_plugin_manager_window.html", null ],
            [ "PluginSettingsWindow", "class_deul_pie_1_1_extra_ink_1_1_editor_1_1_plugins_1_1_plugin_settings_window.html", null ]
          ] ]
        ] ],
        [ "Events", "namespace_deul_pie_1_1_extra_ink_1_1_events.html", [
          [ "Editor", "namespace_deul_pie_1_1_extra_ink_1_1_events_1_1_editor.html", [
            [ "EventChannelEditorWindow", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_editor_1_1_event_channel_editor_window.html", null ]
          ] ],
          [ "BaseEventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_base_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_base_event_channel" ],
          [ "BaseEventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_base_event_channel_listener.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_base_event_channel_listener" ],
          [ "CharacterEventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_character_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_character_event_channel" ],
          [ "CharacterEventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_character_event_channel_listener.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_character_event_channel_listener" ],
          [ "DialogueEventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_dialogue_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_dialogue_event_channel" ],
          [ "EventChannelBridge", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_event_channel_bridge.html", null ],
          [ "EventChannelManager", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_event_channel_manager.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_event_channel_manager" ],
          [ "EventChannelUsageExample", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_event_channel_usage_example.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_event_channel_usage_example" ],
          [ "FloatEventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_float_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_float_event_channel" ],
          [ "GameObjectEventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_game_object_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_game_object_event_channel" ],
          [ "IntEventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_int_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_int_event_channel" ],
          [ "StringEventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_string_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_string_event_channel" ],
          [ "StringEventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_string_event_channel_listener.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_string_event_channel_listener" ],
          [ "Vector3EventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_vector3_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_vector3_event_channel" ],
          [ "VoidEventChannel", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_void_event_channel.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_void_event_channel" ],
          [ "VoidEventChannelListener", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_void_event_channel_listener.html", "class_deul_pie_1_1_extra_ink_1_1_events_1_1_void_event_channel_listener" ]
        ] ],
        [ "Plugins", "namespace_deul_pie_1_1_extra_ink_1_1_plugins.html", [
          [ "BaseExtraInkPlugin", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_base_extra_ink_plugin.html", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_base_extra_ink_plugin" ],
          [ "DatabaseProvider", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_database_provider.html", null ],
          [ "EventSystemProvider", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_event_system_provider.html", null ],
          [ "IDatabaseProvider", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_database_provider.html", null ],
          [ "IEventSystemProvider", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_event_system_provider.html", null ],
          [ "IExtraInkPlugin", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_extra_ink_plugin.html", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_extra_ink_plugin" ],
          [ "IManagerProvider", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_manager_provider.html", null ],
          [ "IPluginConfig", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_plugin_config.html", null ],
          [ "IPluginConfigStorage", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_plugin_config_storage.html", null ],
          [ "IPluginContext", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_plugin_context.html", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_plugin_context" ],
          [ "IPluginLogger", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_plugin_logger.html", null ],
          [ "IPluginMessage", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_plugin_message.html", null ],
          [ "IPluginMessageHandler", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_plugin_message_handler.html", null ],
          [ "IPluginMessenger", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_plugin_messenger.html", null ],
          [ "IUnityObjectHelper", "interface_deul_pie_1_1_extra_ink_1_1_plugins_1_1_i_unity_object_helper.html", null ],
          [ "ManagerProvider", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_manager_provider.html", null ],
          [ "PluginConfig", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_config.html", null ],
          [ "PluginConfigStorage", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_config_storage.html", null ],
          [ "PluginContext", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_context.html", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_context" ],
          [ "PluginLogger", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_logger.html", null ],
          [ "PluginManager", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_manager.html", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_manager" ],
          [ "PluginMessenger", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_messenger.html", null ],
          [ "PluginMetadata", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_metadata.html", null ],
          [ "PluginStatus", "struct_deul_pie_1_1_extra_ink_1_1_plugins_1_1_plugin_status.html", null ],
          [ "SerializableDictionary< TKey, TValue >", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_serializable_dictionary-2-g.html", null ],
          [ "UnityObjectHelper", "class_deul_pie_1_1_extra_ink_1_1_plugins_1_1_unity_object_helper.html", null ]
        ] ]
      ] ]
    ] ],
    [ "IceCreamPie", "namespace_ice_cream_pie.html", [
      [ "Tweening", "namespace_ice_cream_pie_1_1_tweening.html", [
        [ "ICPSequence", "class_ice_cream_pie_1_1_tweening_1_1_i_c_p_sequence.html", null ],
        [ "ICPTween", "class_ice_cream_pie_1_1_tweening_1_1_i_c_p_tween.html", null ],
        [ "TweenHelper", "class_ice_cream_pie_1_1_tweening_1_1_tween_helper.html", null ]
      ] ]
    ] ],
    [ "사용예제", "class사�예�.html", null ],
    [ "AnimatorCharacterComponent", "class_animator_character_component.html", "class_animator_character_component" ],
    [ "AudioClipData", "class_audio_clip_data.html", null ],
    [ "AudioDatabase", "class_audio_database.html", null ],
    [ "AudioSettings", "struct_audio_settings.html", null ],
    [ "AudioState", "struct_audio_state.html", null ],
    [ "BaseCharacterComponent", "class_base_character_component.html", "class_base_character_component" ],
    [ "BaseCharacterController", "class_base_character_controller.html", "class_base_character_controller" ],
    [ "CameraManager", "class_camera_manager.html", null ],
    [ "Character", "class_character.html", "class_character" ],
    [ "CharacterData", "class_character_data.html", "class_character_data" ],
    [ "CharacterDatabase", "class_character_database.html", null ],
    [ "CharacterDisplay", "class_character_display.html", "class_character_display" ],
    [ "CharacterManager", "class_character_manager.html", "class_character_manager" ],
    [ "DialogueHistoryEntry", "class_dialogue_history_entry.html", null ],
    [ "DialogueManager", "class_dialogue_manager.html", "class_dialogue_manager" ],
    [ "DialogueStyle", "class_dialogue_style.html", null ],
    [ "DialogueStyleAsset", "class_dialogue_style_asset.html", null ],
    [ "DIBootstrapper", "class_d_i_bootstrapper.html", "class_d_i_bootstrapper" ],
    [ "DIContainer", "class_d_i_container.html", "class_d_i_container" ],
    [ "DIUsageExample", "class_d_i_usage_example.html", "class_d_i_usage_example" ],
    [ "ExampleServiceWithDI", "class_example_service_with_d_i.html", "class_example_service_with_d_i" ],
    [ "ExtraInkWindow", "class_extra_ink_window.html", "class_extra_ink_window" ],
    [ "GameEventBridge", "class_game_event_bridge.html", null ],
    [ "GameEventListener", "class_game_event_listener.html", null ],
    [ "GameEventsUsageExample", "class_game_events_usage_example.html", null ],
    [ "IAudioManager", "interface_i_audio_manager.html", "interface_i_audio_manager" ],
    [ "IAudioService", "interface_i_audio_service.html", "interface_i_audio_service" ],
    [ "ICharacterAnimator", "interface_i_character_animator.html", "interface_i_character_animator" ],
    [ "ICharacterController", "interface_i_character_controller.html", "interface_i_character_controller" ],
    [ "ICharacterManager", "interface_i_character_manager.html", "interface_i_character_manager" ],
    [ "ICharacterRenderer", "interface_i_character_renderer.html", "interface_i_character_renderer" ],
    [ "ICharacterService", "interface_i_character_service.html", "interface_i_character_service" ],
    [ "ICPTweenCharacterAnimator", "class_i_c_p_tween_character_animator.html", "class_i_c_p_tween_character_animator" ],
    [ "IDialogueManager", "interface_i_dialogue_manager.html", "interface_i_dialogue_manager" ],
    [ "IDialogueService", "interface_i_dialogue_service.html", "interface_i_dialogue_service" ],
    [ "IDIContainer", "interface_i_d_i_container.html", "interface_i_d_i_container" ],
    [ "IEventService", "interface_i_event_service.html", "interface_i_event_service" ],
    [ "Ink_Start", "class_ink___start.html", null ],
    [ "InkCharacterBridge", "class_ink_character_bridge.html", null ],
    [ "InkStoryManager", "class_ink_story_manager.html", "class_ink_story_manager" ],
    [ "InputActions", "class_input_actions.html", "class_input_actions" ],
    [ "IService", "interface_i_service.html", "interface_i_service" ],
    [ "IUnityService", "interface_i_unity_service.html", "interface_i_unity_service" ],
    [ "LanguageSelector", "class_language_selector.html", null ],
    [ "LocalizationManager", "class_localization_manager.html", null ],
    [ "SaveData", "class_save_data.html", null ],
    [ "SaveLoadManager", "class_save_load_manager.html", null ],
    [ "SceneManager", "class_scene_manager.html", null ],
    [ "SerializableDictionary", "class_serializable_dictionary.html", null ],
    [ "SimpleAnimatorCharacterComponent", "class_simple_animator_character_component.html", "class_simple_animator_character_component" ],
    [ "SimpleSpriteCharacterComponent", "class_simple_sprite_character_component.html", "class_simple_sprite_character_component" ],
    [ "SpriteCharacterController", "class_sprite_character_controller.html", "class_sprite_character_controller" ],
    [ "SpriteCharacterRenderer", "class_sprite_character_renderer.html", "class_sprite_character_renderer" ],
    [ "StoryData", "class_story_data.html", "class_story_data" ],
    [ "StoryDatabase", "class_story_database.html", "class_story_database" ],
    [ "StorySelector", "class_story_selector.html", "class_story_selector" ],
    [ "StoryStarter", "class_story_starter.html", "class_story_starter" ],
    [ "StyleManager", "class_style_manager.html", "class_style_manager" ],
    [ "TextAnimationData", "class_text_animation_data.html", null ],
    [ "TextAnimationSystem", "class_text_animation_system.html", "class_text_animation_system" ]
];